import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menubar } from "primereact/menubar";
import { PrimeReactProvider } from "primereact/api";
import MySidebar from "@/components/Sidebar";
import { Button } from "primereact/button";
import MyMenubar from "@/components/MyMenubar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider>
          {/* <Navbar /> */}
          <MyMenubar/>
          <MySidebar/>
          <main className="p-4">{children}</main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
